### PR TITLE
Fix the submitted cursor does not meet the pulsar subscription expectations.

### LINKED ISSUE #367: [BUG] Repeat consumption last message
When `external-subscription` mode used, caused repeat consumption.

### LINKED ISSUE #370: [BUG] In the subscription mode, the first message is lost at the first startup.
**Describe the bug**

If you use an existing subscription and start using the subscription mode of the connector, the first message will be lost.

**To Reproduce**
1. Create a subscriber for the topic, write 1-100 messages to the topic,
2. Let Consumer of pulsar-client use this subscriber's message.
3. Write 1-100 messages to the topic again.
4. Use the Pulsar-flink connector subscription mode to start, and the first consumed message is lost.

**Expected behavior**
With existing subscribers, the first message will not be lost.

**Screenshots**

**Additional context**

When the connector submits the cursor to pulsar, the submitted cursor is the last message currently consumed. Pulsar admin defaults that the current message is the first message of the next consumption.

In the connector, the first message is lost by default, which is also the reason for the problem.
**The root cause is that the cursor submitted by the connector does not comply with pulsar's rules**, resulting in inconsistent behavior.

### PR DESCRIPTION
**Pull request by jianyun8023**
- fixed #367
- fixed #370

### CODE REVIEW

**Comment by jianyun8023** [comment]
@shibd @gaozhangmin Can you review it for me?

**Comment by shibd** [comment]
@jianyun8023 Unit test failed

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarMetadataReader.java [hunk 1]
```diff
@@ -245,7 +245,7 @@ public void commitOffsetToCursor(Map<TopicRange, MessageId> offset) {
             TopicRange tp = entry.getKey();
             try {
                 log.info("Committing offset {} to topic {}", entry.getValue(), tp);
-                admin.topics().resetCursor(tp.getTopic(), subscriptionNameFrom(tp), entry.getValue());
+                admin.topics().resetCursor(tp.getTopic(), subscriptionNameFrom(tp), entry.getValue(), true);
```
Comment (shibd) [inline pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarMetadataReader.java:248]: Why change here? It causes unit tests to fail.

`TopicReaderTest#testCommitOffsetsToPulsar`

Comment (jianyun8023) [reply pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarMetadataReader.java:248]: The modification here is to make the submitted cursor meet the expectations of pulsar subscription, you can pay attention to issue #370

Comment (shibd) [reply pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarMetadataReader.java:248]: Ok, Unit testing needs to be fixed. 

ExpectedId In `TopicReaderTest#testCommitOffsetsToPulsar`  test method  Should be changed to `Last message entryId + 1`

image

Comment (gaozhangmin) [reply pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarMetadataReader.java:248]: I have a doubt, Since, We had reset cursor offset with exclusion. What's the meaning of param `excludeMessageId` in readerThread

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/ReaderThread.java [hunk 2]
```diff
@@ -142,31 +140,26 @@ protected void createActualReader() throws PulsarClientException {
         reader = readerBuilder.create();
     }
 
-    protected void handleUnAvailedCursor() throws PulsarClientException {
+    protected void handleUnAvailedStartMessageId() throws PulsarClientException {
```
Comment (nlu90) [inline pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/ReaderThread.java:143]: what's the meaning of `UnAvailed`?

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarMetadataReader.java (hunk 1 above)
Comment (nlu90) [reply pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarMetadataReader.java:248]: Should this be decided by the `StartupMode` or we always want to exclude the first message?

**Review by nlu90 — CHANGES_REQUESTED** [review]

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarMetadataReader.java (hunk 1 above)
Comment (jianyun8023) [reply pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/PulsarMetadataReader.java:248]: @gaozhangmin @nlu90  The `excludeMessageId` is initially used to restore the offset from the flink state, because the location where the flink state is saved must be processed.

But it is also used in subscription mode activation. The cursor (referred to as NextMessageId) to obtain the first message to be read from the subscriber when the task is started. In the next, this cursor will be used to create a Reader consumer, and `excludeStartMessageId = true`. There are two situations:
1.  The subscriber's cursor is already the last message. The NextMessageId obtained must be greater than the latest message Id. Due to the check and processing of the cursor position, in this case, the latest message Id will be set to the startMessageId of the reader.
2.  There is data behind the subscriber's cursor. In this case, NextMessageId will be set to startMessageId.

**The startMessageId of Pulsar Reader achieved consistent performance in both cases.**

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/ReaderThread.java (hunk 2 above)
Comment (jianyun8023) [reply pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/ReaderThread.java:143]: @nlu90 StartMessageId may have an invalid value. In this case, it should be handled according to the rules. Do you have any better suggestions for this method name?

**Comment by jianyun8023** [comment]
> Should this be decided by the StartupMode or we always want to exclude the first message?

@nlu90 The change here is to make the subscriber's cursor position correct.
What is affected is the subscription model. For other modes, this cursor is irrelevant, or not needed.

For the problem of excluding the first message, see here https://github.com/streamnative/pulsar-flink/pull/371#discussion_r665480974

**Comment by jianyun8023** [comment]
@gaozhangmin I updated the code. StartMessageId is not excluded in subscription mode. The logic of comparing startMessageId and latestMessageId has been adjusted. Can you check it out for me?

**Comment by gaozhangmin** [comment]
> @gaozhangmin I updated the code. StartMessageId is not excluded in subscription mode. The logic of comparing startMessageId and latestMessageId has been adjusted. Can you check it out for me?

I think we don't need excludeMessageId flag in readThread any more,  since  excludeMessageId always false.

**Comment by jianyun8023** [comment]
@gaozhangmin No, when restore from the checkpoint or savepoint, you need to start with the next message.  So this judgment is needed.  The cursors that have been successfully processed are stored in checkpoint.

**Review by gaozhangmin — APPROVED** [review]

**Comment by jianyun8023** [comment]
@codelipenghui

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/util/MessageIdUtils.java [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+
+    /**
+     * BatchMessageIdImpl Operate.
+     */
+    public static class BatchMessageIdImplOperate implements MessageIdOperate<BatchMessageIdImpl> {
+
+        @Override
+        public MessageId next(BatchMessageIdImpl current) {
+            if (current.getBatchSize() < 0 || current.getBatchIndex() + 1 > current.getBatchSize()) {
+                return new BatchMessageIdImpl(current.getLedgerId(), current.getEntryId() + 1, current.getPartitionIndex(), -1);
```
Comment (codelipenghui) [inline pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/util/MessageIdUtils.java:85]: If a nonexistent message ID can work for the Flink connector, it's ok, because the next message might in the next Ledger, not the current ledger.

Comment (jianyun8023) [reply pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/util/MessageIdUtils.java:85]: ok.

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/ReaderThread.java (hunk 2 above)
Comment (jianyun8023) [reply pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/ReaderThread.java]: @nlu90 I have modified it, do you think it is feasible?

**Review by nlu90 — APPROVED** [review]
