### PR TITLE
fix Producer init bug , it should be batchingMaxBytes

### LINKED ISSUE #276: [BUG]  wrong method batchingMaxMessages use when init FlinkPulsarSinkBase producer
**Describe the bug**
it should be batchingMaxBytes here

### LINKED ISSUE #278: [BUG] flink sql case, key will replaced by null ,When the key content is not in the message body
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by holmes07**
fix #276 
fix #278

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/table/DynamicPulsarDeserializationSchema.java [hunk 1]
```diff
@@ -288,16 +288,16 @@ private void emitRow(@Nullable GenericRowData physicalKeyRow, @Nullable GenericR
...
-            }
-
             if (physicalValueRow != null) {
                 for (int valuePos = 0; valuePos < valueProjection.length; valuePos++) {
                     producedRow.setField(valueProjection[valuePos], physicalValueRow.getField(valuePos));
                 }
             }
+            
+             for (int keyPos = 0; keyPos < keyProjection.length; keyPos++) {
+                assert physicalKeyRow != null;
```
Comment (syhily) [inline pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/table/DynamicPulsarDeserializationSchema.java:298]: Should we just use `Preconditions.checkNotNull(physicalKeyRow)`
This would throw a `NullPointerException` instead of a puzzled AssertionError.

**Review by syhily — APPROVED** [review]

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/table/DynamicPulsarDeserializationSchema.java [hunk 2]
```diff
@@ -288,16 +288,16 @@ private void emitRow(@Nullable GenericRowData physicalKeyRow, @Nullable GenericR
...
+                producedRow.setField(keyProjection[keyPos], physicalKeyRow.getField(keyPos));
+            }
```
Comment (jianyun8023) [inline pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/table/DynamicPulsarDeserializationSchema.java:300]: Please use the command `mvn license:check checkstyle:check` to check your code, you have a messed up style here.
```
2021-03-25T09:41:53.1187470Z [INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ pulsar-flink-connector-2.11-1.12 ---
2021-03-25T09:41:56.3645269Z [INFO] There is 1 error reported by Checkstyle 8.18 with /tools/maven/checkstyle.xml ruleset.
2021-03-25T09:41:56.3716041Z [ERROR] src/main/java/org/apache/flink/streaming/connectors/pulsar/table/DynamicPulsarDeserializationSchema.java:[304] (regexp) RegexpSingleline: Trailing whitespace
```

**Review by jianyun8023 — CHANGES_REQUESTED** [review]

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/table/DynamicPulsarDeserializationSchema.java (hunk 1 above)
Comment (holmes07) [reply pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/table/DynamicPulsarDeserializationSchema.java:298]: physicalKeyRow will not throw an exception here. i mean physicalValueRow will use a null value to set the key pos field value. so we should use physicalKeyRow.getField(keyPos) to correct it later. that't why i  Change the order of two pieces of code

File: pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/table/DynamicPulsarDeserializationSchema.java (hunk 2 above)
Comment (holmes07) [reply pulsar-flink-connector/src/main/java/org/apache/flink/streaming/connectors/pulsar/table/DynamicPulsarDeserializationSchema.java]: done

**Review by jianyun8023 — APPROVED** [review]
